#ifndef KF_ALTITUDE_CONSTANTS_H
#define KF_ALTITUDE_CONSTANTS_H

#define EARTH_ACCELERATION 9.81f


//Initial Uncertainty
#define DELTA_INITIAL_ALTITUDE 1.0f
#define DELTA_INITIAL_VELOCITY 10.0f
#define DELTA_INITIAL_ACCELERATION 100.0f

//Three sigma rule
#define RHO_SQUARED_INITIAL_ALTITUDE_UNCERTAINTY DELTA_INITIAL_ALTITUDE * DELTA_INITIAL_ALTITUDE
#define RHO_SQUARED_INITIAL_VELOCITY_UNCERTAINTY DELTA_INITIAL_VELOCITY * DELTA_INITIAL_VELOCITY
#define RHO_SQUARED_INITIAL_ACCELERATION_UNCERTAINTY DELTA_INITIAL_ACCELERATION * DELTA_INITIAL_ACCELERATION


//Process noise
#define NOISE_ALTITUDE 0.01f
#define NOISE_VELOCITY 0.02f
#define NOISE_ACCELERATION 0.001f

//One sigma rule
#define RHO_SQUARED_INITIAL_ALTITUDE_NOISE NOISE_ALTITUDE * NOISE_ALTITUDE
#define RHO_SQUARED_INITIAL_VELOCITY_NOISE NOISE_VELOCITY * NOISE_VELOCITY
#define RHO_SQUARED_INITIAL_ACCELERATION_NOISE NOISE_ACCELERATION * NOISE_ACCELERATION


//RMS: Sensor Noise
#define RMS_ALTITUDE 0.06f
#define RMS_ACCELERATION 0.003f

//One sigma rule
#define RHO_SQUARED_ALTITUDE_RMS RMS_ALTITUDE * RMS_ALTITUDE
#define RHO_SQUARED_ACCELERATION_RMS RMS_ACCELERATION * RMS_ACCELERATION


#endif
